name: 📤 نشر تلقائي إلى ORCID

on:
  workflow_dispatch:
  push:
    paths:
      - feed.xml

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      ORCID_ID: ${{ secrets.ORCID_ID }}
      ORCID_TOKEN: ${{ secrets.ORCID_TOKEN }}

    steps:
      - name: 🔽 Checkout repository
        uses: actions/checkout@v4

      - name: 📦 Install dependencies
        run: npm install xml2js axios

      - name: 🚀 Run publish-to-orcid.js
        run: node publish-to-orcid.js
